### ISSUE TITLE
Consider following TAG recommendations for naming JSON fields

### ISSUE THREAD

**Issue by domenic** [WICG/reporting#72]
See https://w3ctag.github.io/design-principles/#casing-rules. Basically, I see a lot of dashes, but elsewhere on the web platform we've used underscores.

There might a conflict here with IETF practice for header fields. Even if we keep dashes for JSON fields in headers, probably we should use underscores for message bodies. (In this case I think the only thing impacted is the examples' `body` values.)

**Comment by domenic** [comment]
https://github.com/WICG/reporting/blob/master/EXPLAINER.md also needs updating. It uses a third convention, camelCase!

(Also it uses sourceFile instead of url, which is strange.)

**Comment by RByers** [comment]
Changing all the dashes to underscores if that's really more common in JSON sounds fine with me, but that would make generic reporting deviate from CSP which it was designed to generalize so I defer to @mikewest's judgement on that.

Regardless, the camelCase names  I sketched out in the explainer and use of `sourceFile` (which I kind of modeled after Error.fileName) instead of `url` should probably just be changed as Domenic describes (either dash or underscore - whichever we agree on above).  @paulmeyer90 want to do just do that?

**Comment by RByers** [comment]
@patrickkettner any thoughts?  We're probably getting close to shipping this, so the time for name bikeshedding is now :-)

**Comment by mikewest** [comment]
I wouldn't put CSP forward as a good example of best practices in naming. I think it should be seen as an artifact of a simpler time, predating both the TAG's recommendation specifically, and good taste generally, and . I'm fine with `_` in JSON fields.

**Comment by RByers** [comment]
Thanks Mike!  Paul, can you globally convert all the JSON names to underscore format across the spec as Domenic suggests?  @juliatuttle are you OK changing the chromium implementation?

**Comment by RByers** [comment]
We've agreed to update spec/impl for this, can we call this fixed now?

**Comment by dcreager** [comment]
There is at least one lingering dash-named field (`include-subdomains`, maybe others?) that I'd like to update first before closing this.

**Comment by paulmeyer90** [comment]
As all fields have now been updated, I will close this issue.
