### ISSUE TITLE
"Core" report delivery and predefined report types

### ISSUE THREAD

**Issue by dcreager** [WICG/reporting#80]
We've defined a small number of predefined report types in this spec.  Should we?

The alternative would be that the Reporting API is *only* concerned with report delivery, and that all report types should be defined elsewhere.  We did that from the beginning with Network Error Logging.

I think there would be a couple of benefits to that:

- It's easier to separately ship the implementations of the "core" Reporting spec and the various report types.  (For instance, report delivery is basically ready to go in Chrome, and we need to ship that to be able to ship NEL — but it would feel weird to file an intent to ship for "Reporting excluding §6", or to block shipping NEL because we're not yet ready to ship crash reports.)

- TAG reviews would be able to more clearly target (and block acceptance/implementation of) report delivery vs the report types.

- The core delivery logic is useful even to non-Web-Platform clients (e.g. [nel-reporter-java](/google/nel-reporter-java)).  That's also true of some report types (NEL), but not others (deprecations, interventions).  I think there's value in having a simple Reporting spec, containing the minimum set of functionality needed to deliver reports.

The flip side is that it's onerous to add all of the spec boilerplate to something that's currently 1-2 paragraphs in the Reporting spec.  But I think the clearer separation of concerns would be worthwhile.

**Comment by paulmeyer90** [comment]
What I'd imagined was that some report types (especially those without existing specs, like deprecation, intervention reports) would be specced right in the Reporting spec, while others would be specced in their own (or closely related) specs if they have them (like feature policy violation reports).

**Comment by paulmeyer90** [comment]
I actually hadn't noticed the comments on #60 until just recently, and I've already got the deprecation report type specced out in this spec at the moment. Since I'm aiming to ship ReportingObserver and deprecation reports together (and hopefully relatively soon), I think it would be reasonable to keep them together for now, continue this discussion, and the deprecation report definition could always be extracted out to its own spec later on if that's the way we end up going.

Does that sound reasonable?

**Comment by dcreager** [comment]
Closing this; I think we have a good agreement about where the cutoff should be
